import type { Metadata } from "next";
import { Noto_Sans_Thai } from "next/font/google";
import "./globals.css";
import NextAuthProvider from "@/components/NextAuthProvider";
import ThemeProvider from "@/components/theme/ThemeProvider";

const kanit = Noto_Sans_Thai({
    subsets: ["thai", "latin"],
    display: "swap",
    preload: true,
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

type Props = Readonly<{
    children: React.ReactNode;
}>;

export default function RootLayout({ children }: Props) {
    return (
        <NextAuthProvider session={null}>
            <html lang="en">
                <ThemeProvider>
                    <body className={`${kanit.className} antialiased`}>
                        {children}
                    </body>
                </ThemeProvider>
            </html>
        </NextAuthProvider>
    );
}
