events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    sendfile on;
    keepalive_timeout 65;

    # SSL Configuration
    ssl_certificate /etc/nginx/certs/selfsigned.crt;
    ssl_certificate_key /etc/nginx/certs/selfsigned.key;
    # ssl_certificate /etc/letsencrypt/live/exam-checking.com/fullchain.pem;
    # ssl_certificate_key /etc/letsencrypt/live/exam-checking.com/privkey.pem;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;
    ssl_prefer_server_ciphers on;

    # Default server configurations
    server {
        listen 80 default_server;
        server_name _;
        location / {
            return 404;
        }
    }

    server {
        listen 443 ssl default_server;
        server_name _;
        location / {
            return 404;
        }
    }

    # Common Proxy Configuration
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "Upgrade";


    # Redirect to SSL
    server {
        listen 80;
        server_name exam-checking.com;
        location / {
            return 301 https://$host$request_uri;
        }
    }




    # Service Proxies
    server {
        listen 443 ssl;
        server_name exam-checking.com;
        location / {
            proxy_pass http://frontend_service:3000/;
        }
    }

    server {
        listen 3000 ssl;
        server_name exam-checking.com;
        location / {
            proxy_pass http://users_service:3000/;
        }
    }

    server {
        listen 3001 ssl;
        server_name exam-checking.com;
        location / {
            proxy_pass http://database_service:3000/;
        }
    }

    server {
        listen 3002 ssl;
        server_name exam-checking.com;
        location / {
            client_max_body_size 50M;
            proxy_pass http://image_storage:3000/;
        }
    }

    server {
        listen 3003 ssl;
        server_name exam-checking.com;
        location / {
            proxy_pass http://image_process:8000/;
        }
    }
}
