import React from "react";
import type { Metadata } from "next";
import { Kanit } from "next/font/google";
import MuiCacheProvider from "@/components/providers/MuiCacheProvider";
import MuiThemeProvider from "@/components/providers/MuiThemeProvider";
import { ThemeContextProvider } from "@/components/providers/MuiThemeContextProvider";

const kanit = Kanit({
    subsets: ["latin"],
    weight: "100",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

type Props = {
    children: React.ReactNode;
};

export default function RootLayout({ children }: Props) {
    return (
        <html lang="en">
            <body>
                <MuiCacheProvider>
                    <ThemeContextProvider>
                        <MuiThemeProvider>{children}</MuiThemeProvider>
                    </ThemeContextProvider>
                </MuiCacheProvider>
            </body>
        </html>
    );
}
